name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: cleanup for release
        run: |
          rm -f ./test* ./inspect.mjs
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: env TAG_NAME=`echo $GITHUB_REF | cut -d / -f3` node -e 'process.stdin.on("data",(c)=>{p=JSON.parse(c.toString("utf8"));p.version=process.env.TAG_NAME;process.stdout.write(JSON.stringify(p))})' < ./package.json
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
