name: test module

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: execute test
        id: execute_test
        run: |
          TAG_NAME=`echo $GITHUB_REF | cut -d / -f3`
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          VERSION=`echo $TAG_NAME | cut -c1-`
          echo "version_for_setup=$VERSION" >> $GITHUB_OUTPUT
          echo "tag: $TAG_NAME  version: $VERSION"
      - name: test outputs
        run: |
          echo "TAG: ${{steps.execute_test.outputs.tag_name}}"
          echo "VERSION: ${{steps.execute_test.outputs.version_for_setup}}"
          