name: test module

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: execute test
        id: test_tags
        run: |
          TAG_NAME=`echo $GITHUB_REF | cut -d / -f3`
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          VERSION=`echo $TAG_NAME | cut -c1-`
          echo "version_for_setup=$VERSION" >> $GITHUB_OUTPUT
          echo "tag: $TAG_NAME  version: $VERSION"
      - name: test outputs
        run: |
          echo "TAG: ${{steps.test_tags.outputs.tag_name}}"
          echo "VERSION: ${{steps.test_tags.outputs.version_for_setup}}"
      - name: unit tests
        run: |
          ls -a
          npm ci
          mv -vf test/jpg.js node_modules/image-size/dist/types/  # temporary until https://github.com/image-size/image-size/pull/424 gets into a release on npm
          mv -vf test/full.umd.js node_modules/exifr/dist/  # temporary until https://github.com/MikeKovarik/exifr/pull/132 lands on npm
          timedatectl status
          npm test
        env:
          PDB_URL_HTTP: ${{ secrets.PDB_URL_HTTP }}
          PDB_URL_S3_PUBLIC: ${{ secrets.PDB_URL_S3_PUBLIC }}
          PDB_URL_S3_PRIVATE: ${{ secrets.PDB_URL_S3_PRIVATE }}
          PDB_URL_S3_REGION: ${{ secrets.PDB_URL_S3_REGION }}
          PDB_URL_S3_PRIVATE_ACCESS_KEY_ID: ${{ secrets.PDB_URL_S3_PRIVATE_ACCESS_KEY_ID }}
          PDB_URL_S3_PRIVATE_SECRET_KEY: ${{ secrets.PDB_URL_S3_PRIVATE_SECRET_KEY }}
